# this file controls the amount of output
# rename to config.yml to make it effective

# prefix for output filenames
name: urmel
# write problem files in the lp-format?
write_lp: False
# write solution files in the sol-format?
write_sol: False
# write irreducible infeasibility set if problem is infeasible? 
write_ilp: False
# write wheel maps with gnuplot?
gnuplot: False
# console output?
urmel_console_output: True
# gurobi logfile
grb_logfile: gurobi.log
# gurobi console output 
grb_console: True
